### ISSUE TITLE
Delete stub in GUI does not refresh

### ISSUE THREAD

**Issue by Martin-Mol** [dukeofharen/httplaceholder#120]
the stubb list is updated, by removing the deleted stub. 
The selected stubb is also updated, because the previous selected stubb is gone.
The stub details are NOT updated.
therefore it looks like the old stub is not deleted.
Deleting the stub 'again' results in deleting the new selected, but not shown stub.

result stub loss. :(

**Comment by Martin-Mol** [comment]
version 2021.3.13.194

**Comment by dukeofharen** [comment]
@Martin-Mol If I understand correctly, when you delete an old stub, the UI will open the next stub in line. It then looks like the old stub isn't deleted, but it is. Is that correct?

![1](https://user-images.githubusercontent.com/6454138/112654877-26896b00-8e50-11eb-93e6-b42417f57957.png)
![2](https://user-images.githubusercontent.com/6454138/112654881-27ba9800-8e50-11eb-895b-1032cb10743d.png)
![3](https://user-images.githubusercontent.com/6454138/112654886-27ba9800-8e50-11eb-935a-4a7565cb6df9.png)

This is a bit confusing indeed, it may be better if, when you delete an old stub, all stubs are closed on the overview screen.

**Comment by Martin-Mol** [comment]
Yes correct.
If you click on the stub, to collapse the stub view and click again to expand, the correct stub details are shown.

Indeed closing the stub after delete wil solve the issue.

**Comment by dukeofharen** [comment]
The issue is fixed in the latest release 2021.3.27.223

**Comment by Martin-Mol** [comment]
great! tnx
