### ISSUE TITLE
Database table same column size

### ISSUE THREAD

**Issue by LotteVoorhorst** [dukeofharen/httplaceholder#147]
**Problem**
When using a sql database as a persistent storage option, there's a difference between column sizes in the following tables: 

- dbo.Requests > **executing_stub_id**  -> nvarchar(100) 
- dbo.Stubs > **stub_id** -> nvarchar(255) 

This throws an exception when saving the request to the database: 

**System.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated in table** 

This should be the same amount of characters.

**Comment by dukeofharen** [comment]
Hi,

Thanks Lotte for reporting the issue. This indeed seems an inconsistency in the database schema. I will take a look at it.

**Comment by dukeofharen** [comment]
Forgot to mention it, but this bug has been fixed and a new release has been made.
