### ISSUE TITLE
UI: add categories

### ISSUE THREAD

**Issue by wpeterw** [dukeofharen/httplaceholder#2]
Would it be possible to have stub categories and group stubs by categorie in the UI ? Nice to have: make these categories collapsible/extendable in the UI.

**Comment by dukeofharen** [comment]
hi @wpeterw, yes, I think that's possible. HttPlaceholder already contains something called "tenants" (see https://github.com/dukeofharen/httplaceholder/blob/master/docs/API.md). This is a property you can set on you stub to do batch operations with it (e.g. delete all stubs in a tenant, get all stubs in a tenant etc.). I think I can create something so you can group the requests in the UI by tenant, or something like that.

If time permits it, I will take a look at it.

**Comment by dukeofharen** [comment]
Hi @wpeterw,

With the new release, it is now possible to see the stubs and requests sorted by tenant in the UI. To set a tenant (which you could also call category), see this example: https://github.com/dukeofharen/httplaceholder/blob/master/docs/samples/01-get.yml. You can download the latest version here: https://github.com/dukeofharen/httplaceholder/releases/tag/v2019.9.9.142
