### ISSUE TITLE
Disable CORS

### ISSUE THREAD

**Issue by ilteoood** [dukeofharen/httplaceholder#38]
Hi!
Is it possibile to disable CORS with a single flag, instead of repeat the headers in every mock?

Matteo

**Comment by dukeofharen** [comment]
Hello Matteo,

Unfortunately, that's not possible at the time. If you want to use CORS for your requests, you have to copy/paste the headers for every request right now. I've made a new issue though: https://github.com/dukeofharen/httplaceholder/issues/39. I've got no estimate right now at when this will be done though. This was on my todo list for some time, but I guess it's better if I add my todo items to GitHub issues one by one so anyone can see what the roadmap is.

Anyway, thanks for your question and your support!
