### ISSUE TITLE
Host in IIS, where is _web.config ?

### ISSUE THREAD

**Issue by wpeterw** [dukeofharen/httplaceholder#41]
Installed httplaceholder with:

`Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/dukeofharen/httplaceholder/master/scripts/Install-Windows.ps1'))`

The documentation says: 

`Additionally, two additional files are also installed on the machine: _config.json and _web.config. If you want to host the application in IIS, you have to remove the _ from the filename. The _ is added to the files so the actual configuration files won't be overwritten if a new version of HttPlaceholder is installed`

Where are these files located ?

**Comment by dukeofharen** [comment]
Hi @wpeterw,

Unfortunately, I just came across an issue where the previous release did not go well but all lights were green. I'm going to fix that asap. For now, you can download the older release: https://github.com/dukeofharen/httplaceholder/releases/download/v2020.08.23.62/httplaceholder_win-x64.zip.

I will keep you informed.

Regards

**Comment by dukeofharen** [comment]
Hi @wpeterw,

I've released a new version. Can you try running the installation script again and see if it works? I've tested it and it seems to work fine.

Regards
